runtime: nodejs8

handlers:
- url: /public
  static_dir: public
  secure: always
  redirect_http_response_code: 301
- url: /.*
  script: true
  secure: always
  redirect_http_response_code: 301

env_variables:
  BUCKET_NAME: screenshots-microservice-demo